language: Java

install:
#installing sfdx
- wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- mkdir sfdx
- tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
- ./sfdx/install
- sfdx --version
- sfdx plugins
- sfdx force --help
- sfdx commands
